service: centralBotLambda

provider:
  name: aws
  runtime: nodejs10.x
  profile: bot-dev

  environment:
    # AWS configuration
    ACCESS_KEY_ID: FAKE_ACCESS_KEY_ID
    SECRET_ACCESS_KEY: FAKE_SECRET_ACCESS_KEY
    REGION: FAKE_REGION
    DYNAMODB_ENDPOINT: http://localhost:8000

    # TC Slack bot configuration
    ADMIN_USER_TOKEN: xoxp-755656631591-747386116513-907833188438-f42f5df4230bcd906a8d100b5c46d6a3
    BOT_TOKEN: xoxb-755656631591-905169374100-lPUJga4UDqIIRUyphZ7WBjnb
    CHANNEL: general
    CLIENT_SIGNING_SECRET: 16dc7aefe4fc58b91f5010bc170f5664

    # Slack Lambda configuration
    SLACK_LAMBDA_URI: 'http://localhost:3001'

    # Teams lambda configuration
    TEAMS_LAMBDA_URI: 'http://localhost:3002'

    # Topcoder connect configuration
    CONNECT_BEARER_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJUb3Bjb2RlciBVc2VyIl0sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLWRldi5jb20iLCJoYW5kbGUiOiJ0b3Bib3QzIiwiZXhwIjoxNTgwNDUwNDAwLCJ1c2VySWQiOiI0MDE1OTAyMiIsImlhdCI6MTU3NTUxMTk3NywiZW1haWwiOiJiaWxsc2VkaXNvbisyQGdtYWlsLmNvbSJ9.hsRkUW5z3GMWdU1n6__opr7udzKqXV1RiHWiIZBHJSs

    # SNS Configuration
    SNS_ENDPOINT: http://localhost:4000
    SNS_REGION: us-west-2
    SNS_ACCOUNT_ID: 123456789012

    # SNS Topics
    TC_SLACK_EVENTS_TOPIC: tc-slack-events
    TC_SLACK_INTERACTIVE_TOPIC: tc-slack-interactive

functions:
  tc_slack_events:
    handler: src/functions/receiver/events.handler
    description: Handles slack events from TC Slack
    events:
      - http:
          path: slack/events
          method: post

  tc_slack_interactive:
    handler: src/functions/receiver/interactive.handler
    description: Handles slack interactive messages from TC Slack
    events:
      - http:
          path: slack/interactive
          method: post

  request:
    handler: src/functions/request.handler
    description: Create a project with description
    events:
      - http:
          path: request
          method: post

  events:
    handler: src/functions/events.handler
    description: Handles slack events
    events:
      - sns: tc-slack-events

  interactive:
    handler: src/functions/interactive.handler
    description: Handles slack interactive messages
    events:
      - sns: tc-slack-interactive

  accept:
    handler: src/functions/accept.handler
    description: Handles project accept
    events:
      - http:
          path: accept
          method: post

  decline:
    handler: src/functions/decline.handler
    description: Handles project decline
    events:
      - http:
          path: decline
          method: post

  invite:
    handler: src/functions/invite.handler
    description: Handles project invite
    events:
      - http:
          path: invite
          method: post

plugins:
  - serverless-offline
  - serverless-offline-sns

custom:
  serverless-offline-sns:
    port: 4000
    debug: false