swagger: "2.0"
info:
  description: "REST API definitions for Topbot Central TC Lambda"
  version: "1.0.0"
  title: "Topbot - Central TC Lambda"
host: "localhost:3000"
schemes:
- "http"
paths:
  /tc-slack/request:
    post:
      tags:
      - "Request a project with description"
      summary: "Request a project with description"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Project object"
        required: true
        schema:
          $ref: "#/definitions/CreateProject"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Project"
        400:
          description: "Bad request"
        500:
          description: "Internal Server Error"
  /tc-slack/accept:
    post:
      tags:
      - "Accept a project"
      summary: "Accept a project"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Project id"
        required: true
        schema:
          type: "object"
          properties:
            projectId:
              type: "string"
              example: "14c83983-58ac-475a-882e-101d47a0e4ec"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
        500:
          description: "Internal Server Error"
  /tc-slack/decline:
    post:
      tags:
      - "Decline a project"
      summary: "Decline a project"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Project id"
        required: true
        schema:
          type: "object"
          properties:
            projectId:
              type: "string"
              example: "14c83983-58ac-475a-882e-101d47a0e4ec"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
        500:
          description: "Internal Server Error"
  /tc-slack/invite:
    post:
      tags:
      - "Invite email id to a project"
      summary: "Invite email id to a project"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Project id and email id"
        required: true
        schema:
          type: "object"
          properties:
            projectId:
              type: "string"
              example: "14c83983-58ac-475a-882e-101d47a0e4ec"
            email:
              type: "string"
              example: "a@b.com"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
        500:
          description: "Internal Server Error"
  /tc-slack/events:
    post:
      tags:
      - "Slack events"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      summary: "Endpoint for Slack events. Slack posts command requests to this endpoint. It is meant to be used only through Slack."
      responses:
        200:
          description: "OK"
          schema:
            type: "object"
            required:
            - "challenge"
            properties:
              challenge:
                type: "string"
                example: "983-58ac-475a-882e"
        400:
          description: "Bad request"
  /tc-slack/interactive:
    post:
      tags:
      - "Slack interactive components"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      summary: "Endpoint for Slack interactive components. Interactive elements like button and dialogs post to this endpoint when an action is performed on them"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"

definitions:
  Project:
    type: "object"
    properties:
      id:
        type: "string"
        example: "14c83983-58ac-475a-882e-101d47a0e4ec"
      description:
        type: "string"
        example: "Create a slack bot"
      requester:
        type: "string"
        example: "UPK3WLVN0"
      clientSlackThread:
        type: "string"
        example: "1574566449.000200"
      clientSlackChannel:
        type: "string"
        example: "CN34FJLDP"
      tcSlackThread:
        type: "string"
        example: "1574566452.000100"
      teamsConversationId:
        type: "string"
        example: "19:efb4cf20780543aeab5a152a3571e777@thread.skype;messageid=1575819219395"
      platform:
        type: "string"
        example: "slack"
      status:
        type: "string"
        example: "LAUNCHED"
  CreateProject:
    type: "object"
    required:
      - "description"
      - "requester"
      - "clientSlackThread"
      - "clientSlackChannel"
      - "teamsConversationId"
      - "platform"
    properties:
      description:
        type: "string"
        example: "Create a bot"
      requester:
        type: "string"
        example: "Mayur"
      clientSlackThread:
        type: "string"
        example: "1574566449.000200"
      clientSlackChannel:
        type: "string"
        example: "CN34FJLDP"
      teamsConversationId:
        type: "string"
        example: "19:efb4cf20780543aeab5a152a3571e777@thread.skype;messageid=1575819219395"
      platform:
        type: "string"
        example: "slack"
